# Dev shell + pre-commit hooks via dryvist/nix-devenv flakeModules.
#
# Replaces the previous Pattern-B `.envrc` remote-shell setup with a
# local flake that:
#   1. Inherits the terraform dev shell from nix-devenv (terraform,
#      opentofu, tflint, tfsec, trivy, sops, age, pre-commit,
#      jq, yq, aws-vault — see nix-devenv/shells/terraform/default.nix).
#   2. Imports nix-devenv.flakeModules.terraform, which wires up
#      git-hooks.nix + treefmt-nix + the org-wide pre-commit hooks.
#
# Per-repo divergences from the canonical terraform profile:
#   * gitleaks added — this repo had it in the old .pre-commit-config.yaml
#     for credential leak detection.
#
# .tflint.hcl in this repo carries the canonical content from
# dryvist/.github precommit/configs/tflint.hcl — copy synced manually
# (Renovate sync of precommit/configs/ is queued; see dryvist/.github
# precommit/README.md). The AWS plugin previously declared here has
# been dropped because cachix/git-hooks.nix's tflint wrapper can't
# initialize tflint plugins inside the nix-sandboxed hook run.
{
  description = "Self-hosted RunsOn runner infrastructure (AWS Terraform).";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-25.11-darwin";
    flake-parts.url = "github:hercules-ci/flake-parts";
    nix-devenv = {
      url = "github:dryvist/nix-devenv";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    inputs@{
      flake-parts,
      nix-devenv,
      ...
    }:
    flake-parts.lib.mkFlake { inherit inputs; } {
      systems = [
        "aarch64-darwin"
        "x86_64-darwin"
        "x86_64-linux"
        "aarch64-linux"
      ];

      imports = [ nix-devenv.flakeModules.terraform ];

      perSystem =
        {
          lib,
          pkgs,
          system,
          ...
        }:
        {
          devShells.default = nix-devenv.devShells.${system}.tofu or nix-devenv.devShells.${system}.terraform;

          # Files regenerated by other tooling or vendored from upstream —
          # treefmt would create churn loops or diverge from upstream.
          #   .github/workflows/*.lock.yml  — gh-aw compile output
          #   .github/aw/imports/**         — vendored gh-aw imports keyed by hash
          #   CHANGELOG.md                  — release-please output
          #   aqua-checksums.json           — aqua-cli output
          treefmt.settings.global.excludes = [
            ".github/workflows/*.lock.yml"
            ".github/aw/imports/**"
            "CHANGELOG.md"
            "aqua-checksums.json"
          ];

          pre-commit.settings.hooks = {
            # gitleaks is not in cachix/git-hooks.nix's supported set yet,
            # so wire it manually here. A follow-up adds it to nix-devenv's
            # base profile so this stanza can disappear.
            gitleaks = {
              enable = true;
              name = "gitleaks";
              entry = "${pkgs.gitleaks}/bin/gitleaks protect --verbose --redact --staged";
              language = "system";
              pass_filenames = false;
            };

            # cachix/git-hooks.nix wraps tflint with a per-file script that
            # drops any args beyond $1, breaking the profile's
            # `--config <sharedConfigs.tflint>` plumbing. Until the wrapper
            # accepts pass-through args, fall back to tflint's local-config
            # discovery and keep a copy of the canonical .tflint.hcl in
            # this repo (synced from dryvist/.github precommit/configs/).
            tflint.args = lib.mkForce [ ];

            # terraform-validate needs `tofu init` to download referenced
            # modules from the registry. nix flake check runs hooks in a
            # network-less sandbox so init fails. The validate already
            # runs in CI under OIDC (terraform-checks-placement.md), and
            # interactive `pre-commit run` in the dev shell still works
            # — disabling only the sandboxed flake-check path.
            terraform-validate.enable = lib.mkForce false;
          };
        };
    };
}
